#!/usr/bin/env bash
#
# Trafika kiosk setup — po bootu RPi automaticky otevře fullscreen /qr ve Chromium.
#
# Spouštěj **jako běžný uživatel** (ne root) — kiosk poběží pod tímto uživatelem.
# Vyžaduje Raspberry Pi OS s desktopem (Bookworm s labwc/LXDE, nebo starší s LXDE).
# Na headless instalaci tento skript nepotřebuješ.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/michalvarys/rpi-vending-controller/main/scripts/install-kiosk.sh -o install-kiosk.sh
#   bash install-kiosk.sh

set -euo pipefail

log()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m!!\033[0m  %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -ne 0 ]] || die "Spusť jako běžný uživatel (ne root). Skript zavolá sudo jen tam, kde je potřeba."

# --- 1. Instalace balíčků (chromium + unclutter pro schování kurzoru) ---
need_install=()
command -v chromium >/dev/null 2>&1 || command -v chromium-browser >/dev/null 2>&1 || need_install+=(chromium)
command -v unclutter >/dev/null 2>&1 || need_install+=(unclutter)
if [[ ${#need_install[@]} -gt 0 ]]; then
  log "Instaluji: ${need_install[*]}"
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "${need_install[@]}"
fi

CHROMIUM_BIN=$(command -v chromium 2>/dev/null || command -v chromium-browser 2>/dev/null)
log "Chromium: $CHROMIUM_BIN"

# --- 2. Wrapper skript, který čeká na API a pak spouští Chromium ---
mkdir -p "$HOME/.local/bin"
WRAPPER="$HOME/.local/bin/trafika-kiosk.sh"
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Auto-generated by install-kiosk.sh. Spouští Trafika QR kiosk.
set -e

# Počkej, než naběhne vending controller container (port 8080).
until curl -sf http://localhost:8080/api/health >/dev/null 2>&1; do
  sleep 2
done

# Vypnout spořič obrazovky / DPMS (jen na X, Wayland má vlastní mechanismy).
if command -v xset >/dev/null 2>&1 && [[ -n "\${DISPLAY:-}" ]]; then
  xset s noblank || true
  xset s off || true
  xset -dpms || true
fi

# Skrýt kurzor po 1 s nečinnosti (X; na Wayland je potřeba jiný nástroj).
if command -v unclutter >/dev/null 2>&1 && [[ -n "\${DISPLAY:-}" ]]; then
  unclutter -idle 1 -root &
fi

exec "$CHROMIUM_BIN" \\
  --kiosk \\
  --noerrdialogs \\
  --disable-infobars \\
  --disable-session-crashed-bubble \\
  --disable-features=Translate \\
  --check-for-update-interval=31536000 \\
  http://localhost:8080/qr
EOF
chmod +x "$WRAPPER"
log "Wrapper skript: $WRAPPER"

# --- 3. XDG autostart entry (funguje pro labwc i LXDE) ---
AUTOSTART_DIR="$HOME/.config/autostart"
mkdir -p "$AUTOSTART_DIR"
DESKTOP_FILE="$AUTOSTART_DIR/trafika-kiosk.desktop"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Trafika QR Kiosk
Comment=Fullscreen Chromium s QR kódem pro aktivaci automatu
Exec=/bin/bash $WRAPPER
Terminal=false
X-GNOME-Autostart-enabled=true
EOF
log "Autostart entry: $DESKTOP_FILE"

# --- 4. Zapnout desktop autologin (aby kiosk startoval bez přihlašování) ---
if [[ -x /usr/bin/raspi-config ]]; then
  log "Nastavuji desktop autologin (sudo raspi-config nonint do_boot_behaviour B4)..."
  sudo /usr/bin/raspi-config nonint do_boot_behaviour B4 || \
    warn "raspi-config failed — nastav ručně: sudo raspi-config → System Options → Boot / Auto Login → Desktop Autologin"
else
  warn "raspi-config nenalezen — autologin musíš nastavit ručně (lightdm/labwc)."
fi

# --- 5. Summary ---
cat <<EOF

================================================================
  Trafika kiosk nainstalovaný.

  Co se stane po rebootu:
    1. RPi se nabootuje a automaticky se přihlásí do desktopu.
    2. Wrapper skript čeká, až naběhne trafika-rpi container.
    3. Chromium se otevře fullscreen na http://localhost:8080/qr.

  Ruční spuštění (bez rebootu) — z existující desktop session:
    bash $WRAPPER

  Vypnutí kiosku:
    rm $DESKTOP_FILE
    sudo reboot

  Troubleshooting:
    * Kiosk nestartuje → zkontroluj, jestli se RPi auto-přihlašuje do desktopu
      (systemctl status getty@tty1 → hledej autologin).
    * Chromium zobrazuje "connection refused" → vending controller (port 8080)
      neběží: docker compose ps v /opt/trafika-rpi/.
    * Obrazovka se vypíná / kurzor bliká → zkontroluj xset/unclutter nainstalované.
================================================================
EOF
